destination:    ./_site
paginate:       10
permalink:      /:year/:month/:day/:title.html
auto:           true
lsi:            false
server_port:    4000
pygments:       true
markdown:       maruku
layout:         default
exclude:
    - config.rb


url:            http://travisj.github.com
name:           travisj@github
tagline:        a site about something (maybe)
